name: med_snap
description: "A Flutter application that uses AI to analyze medicines."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # image_picker: ^1.0.4
  http: ^1.1.0
  flutter_dotenv: ^5.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - lib/assets/fonts/  # optional if only used for fonts
    - assets/images/

  fonts:
    - family: KurdiFont
      fonts:
        - asset: lib/assets/fonts/kurdi.ttf

    - family: Noto
      fonts:
        - asset: lib/assets/fonts/NotoSansArabic.ttf